-- MySQL Script generated by MySQL Workbench
-- sex 15 set 2023 12:02:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgcm_prof
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgcm_prof
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgcm_prof` ;
USE `sgcm_prof` ;

-- -----------------------------------------------------
-- Table `sgcm_prof`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_prof`.`usuario` (
  `codigo_usuario` INT NOT NULL,
  `identificacao_usuario` VARCHAR(20) NULL,
  `senha_acesso` VARCHAR(10) NULL,
  `cadastro_usuario` VARCHAR(1) NULL,
  `cadastro_paciente` VARCHAR(1) NULL,
  `cadastro_especialidade` VARCHAR(1) NULL,
  `cadastro_medico` VARCHAR(1) NULL,
  `cadastro_convenio` VARCHAR(1) NULL,
  `agendamento_consulta` VARCHAR(1) NULL,
  `modulo_administrativo` VARCHAR(1) NULL,
  `modulo_agendamento` VARCHAR(1) NULL,
  `modulo_atendimento` VARCHAR(1) NULL,
  `nome_completo` VARCHAR(50) NULL,
  `data_nascimento` DATE NULL,
  `numero_rg` VARCHAR(12) NULL,
  `orgao_emissor` VARCHAR(6) NULL,
  `numero_cpf` VARCHAR(14) NULL,
  `endereco` VARCHAR(45) NULL,
  `numero` VARCHAR(15) NULL,
  `complemento` VARCHAR(30) NULL,
  `bairro` VARCHAR(40) NULL,
  `cidade` VARCHAR(40) NULL,
  `estado` VARCHAR(2) NULL,
  `telefone` VARCHAR(20) NULL,
  `celular` VARCHAR(20) NULL,
  PRIMARY KEY (`codigo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_prof`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_prof`.`especialidades` (
  `codigo_especialidade` INT NOT NULL,
  `descricao_especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_especialidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_prof`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_prof`.`medicos` (
  `codigo_medico` INT NOT NULL,
  `nome_medico` VARCHAR(45) NULL,
  `crm` VARCHAR(20) NULL,
  `codigo_especialidade` INT NOT NULL,
  PRIMARY KEY (`codigo_medico`),
  INDEX `fk_medicos_especialidades_idx` (`codigo_especialidade` ASC) VISIBLE,
  CONSTRAINT `fk_medicos_especialidades`
    FOREIGN KEY (`codigo_especialidade`)
    REFERENCES `sgcm_prof`.`especialidades` (`codigo_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_prof`.`convenios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_prof`.`convenios` (
  `codigo_convenio` INT NOT NULL,
  `empresa_convenio` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`codigo_convenio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_prof`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_prof`.`paciente` (
  `codigo_paciente` INT NOT NULL,
  `identificacao_paciente` VARCHAR(20) NULL,
  `senha_acesso` VARCHAR(10) NULL,
  `nome_completo` VARCHAR(50) NULL,
  `data_nascimento` DATE NULL,
  `numero_rg` VARCHAR(12) NULL,
  `orgao_emissor` VARCHAR(6) NULL,
  `numero_cpf` VARCHAR(14) NULL,
  `endereco` VARCHAR(45) NULL,
  `numero` VARCHAR(15) NULL,
  `complemento` VARCHAR(30) NULL,
  `bairro` VARCHAR(40) NULL,
  `cidade` VARCHAR(40) NULL,
  `estado` VARCHAR(2) NULL,
  `telefone` VARCHAR(20) NULL,
  `celular` VARCHAR(20) NULL,
  `codigo_convenio` INT NOT NULL,
  PRIMARY KEY (`codigo_paciente`, `codigo_convenio`),
  INDEX `fk_paciente_convenios1_idx` (`codigo_convenio` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_convenios1`
    FOREIGN KEY (`codigo_convenio`)
    REFERENCES `sgcm_prof`.`convenios` (`codigo_convenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_prof`.`agenda_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_prof`.`agenda_consulta` (
  `codigo_agenda` INT NOT NULL,
  `data` DATE NULL,
  `hora` TIME NULL,
  `retorno` VARCHAR(1) NULL,
  `cancelado` VARCHAR(1) NULL,
  `motivo_cancelamento` TEXT(500) NULL,
  `codigo_usuario` INT NOT NULL,
  `codigo_medico` INT NOT NULL,
  `codigo_paciente` INT NOT NULL,
  PRIMARY KEY (`codigo_agenda`, `codigo_usuario`, `codigo_medico`, `codigo_paciente`),
  INDEX `fk_agenda_consulta_usuario1_idx` (`codigo_usuario` ASC) VISIBLE,
  INDEX `fk_agenda_consulta_medicos1_idx` (`codigo_medico` ASC) VISIBLE,
  INDEX `fk_agenda_consulta_paciente1_idx` (`codigo_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_agenda_consulta_usuario1`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `sgcm_prof`.`usuario` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_consulta_medicos1`
    FOREIGN KEY (`codigo_medico`)
    REFERENCES `sgcm_prof`.`medicos` (`codigo_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_consulta_paciente1`
    FOREIGN KEY (`codigo_paciente`)
    REFERENCES `sgcm_prof`.`paciente` (`codigo_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_prof`.`prontuario_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_prof`.`prontuario_paciente` (
  `codigo_prontuario` INT NOT NULL,
  `historico` TEXT(500) NULL,
  `receituario` TEXT(500) NULL,
  `exames` TEXT(500) NULL,
  `codigo_agenda` INT NOT NULL,
  PRIMARY KEY (`codigo_prontuario`, `codigo_agenda`),
  INDEX `fk_prontuario_paciente_agenda_consulta1_idx` (`codigo_agenda` ASC) VISIBLE,
  CONSTRAINT `fk_prontuario_paciente_agenda_consulta1`
    FOREIGN KEY (`codigo_agenda`)
    REFERENCES `sgcm_prof`.`agenda_consulta` (`codigo_agenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sgcm_prof`.`especialidades`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgcm_prof`;
INSERT INTO `sgcm_prof`.`especialidades` (`codigo_especialidade`, `descricao_especialidade`) VALUES (1, 'Acupuntura');
INSERT INTO `sgcm_prof`.`especialidades` (`codigo_especialidade`, `descricao_especialidade`) VALUES (2, 'Cardiolologia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgcm_prof`.`convenios`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgcm_prof`;
INSERT INTO `sgcm_prof`.`convenios` (`codigo_convenio`, `empresa_convenio`, `cnpj`, `telefone`) VALUES (1, '100% Saúde', '87.348.381/0001-82', '(16) 3657-0245');
INSERT INTO `sgcm_prof`.`convenios` (`codigo_convenio`, `empresa_convenio`, `cnpj`, `telefone`) VALUES (2, 'Santo Cuidado', '92.415.208/0001-90', '(16) 3763-2045');

COMMIT;

